### ISSUE TITLE
sslverify default value issue

### ISSUE THREAD

**Issue by karthikrev** [chef-cookbooks/yum#111]
As per resources sslverify can take either true or false
resources/repository.rb
  attribute :sslverify, :kind_of => [TrueClass, FalseClass], :default => true
but in template it checks sslverify is nil ..
<% unless @config.sslverify.nil? %>
sslverify=<%= @config.sslverify %>
<% end %>

Because of this when I use the LWRP
sslverify nil     =>  repo file has  sslverify=true

In my opinion 
  attribute :sslverify, :kind_of => [TrueClass, FalseClass], :default => true
should be 
  attribute :sslverify, :kind_of => [TrueClass, FalseClass], :default => nil

**Comment by someara** [comment]
Fixed this up in 3.6.3
