### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by ElijahCaine** [chef-cookbooks/yum#114]
An ongoing issue for testing.

I will do the initial infrastructure which will look similar to https://github.com/chef-cookbooks/yum/blob/master/TESTING.md adjusted to fit our needs.

**Comment by someara** [comment]
ps: that docs needs to be reworked... we don't use travis that way anymore
-s

**Comment by ElijahCaine** [comment]
Oops, I accidentally posted this issue on the wrong repository. Sorry!
