### ISSUE TITLE
tolerant returns "true" string in yum config (and other attributes are amiss)

### ISSUE THREAD

**Issue by tatemz** [chef-cookbooks/yum#116]
Here is an example of my `yum.conf` after a chef run.

My role set the attribute `node["yum"]["main"]["tolerant"]` to `TrueClass`. Note how the value was not turned into a `1` inside of the config.

I also noticed that `multilib_policy` is set in the documentation as an array, but the resource demands a string. Perhaps other config attributes are amiss as well!

```
# This file was generated by Chef
# Do NOT modify this file by hand.

[main]
cachedir=/var/cache/yum/$basearch/$releasever
debuglevel=2
distroverpkg=centos-release
exactarch=1
gpgcheck=1
installonly_limit=3
keepcache=0
logfile=/var/log/yum.log
multilib_policy=best
obsoletes=1
plugins=1
tolerant=true
tsflags=repackage
```

**Comment by someara** [comment]
Hi. This should be fixed up in 02f87e45dcf7ddbc71e918a384cbd27563865ffb
