### ISSUE TITLE
repo_gpgcheck attribute

### ISSUE THREAD

**Issue by jimwise** [chef-cookbooks/yum#121]
As noted here:

http://seven.centos.org/2015/05/signed-repository-metadata-is-now-available-for-centos-6-and-7-for-the-updates-repo/

CentOS repos now make use of gpg-signed repository metadata.  Would be great to be able to set this up with this cookbook (and to turn it on by default in the "cents" cookbook).

**Comment by someara** [comment]
Added in 71893381793e94dc38a039d0288227afdf79b1b2

**Comment by jimwise** [comment]
Awesome.  Thank you,

Jim Wise
jwise@draga.com

Sent from my iPhone.
Digital signature available upon request.
