### ISSUE TITLE
yum makecache fails for resource with remote repository key

### ISSUE THREAD

**Issue by urbanautomaton** [chef-cookbooks/yum#124]
Hi - I'm not certain this is a bug with this cookbook, so apologies in advance if not. I have a problem installing a repository with `repo_gpgcheck = true` without manual intervention.

### Version info:

* Chef 12.3.0
* Centos 7.0
* yum cookbook 3.6.1

### Steps to reproduce:

Converge the following recipe:

```ruby
# somecookbook/recipes/default.rb

yum_repository "passenger" do
  description "Phusion Passenger repository"
  baseurl "https://oss-binaries.phusionpassenger.com/yum/passenger/el/$releasever/$basearch"
  gpgcheck false
  repo_gpgcheck true
  gpgkey "https://packagecloud.io/gpg.key"
end
```

### Output:

```
[2015-06-19T12:31:57+00:00] ERROR: yum_repository[passenger] (somecookbook::default line 14) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[yum-makecache-passenger] (/tmp/kitchen/cookbooks/yum/providers/repository.rb line 61) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of yum -q makecache --disablerepo=* --enablerepo=passenger ----
STDOUT: Is this ok [y/N]:
STDERR: Importing GPG key 0xD59097AB:
 Userid     : "packagecloud ops (production key) <ops@packagecloud.io>"
 Fingerprint: 418a 7f2f b0e1 e6e7 eabf 6fe8 c2e7 3424 d590 97ab
 From       : https://packagecloud.io/gpg.key
https://oss-binaries.phusionpassenger.com/yum/passenger/el/7/x86_64/repodata/repomd.xml: [Errno -1] Gpg Keys not imported, cannot verify repomd.xml for repo passenger
Trying other mirror.
```

The problem appears to be that an interactive prompt is generated, receives the default response and the repo verification fails as a result, preventing the `makecache` call from succeeding. If I manually run the command with `-y` on the node, the recipe then converges successfully:

    $ yum -q makecache -y --disablerepo=* --enablerepo=passenger

FWIW this is how packagecloud's [own cookbook handles it](https://github.com/computology/packagecloud-cookbook/blob/master/providers/repo.rb#L116-L119). Even if I switch the key reference to a local file (even one in `/etc/pki/rpm-gpg`) the prompt still appears and the node fails to converge.

Would a patch adding the `-y` flag to the `makecache` call be considered, or is that barking up completely the wrong tree?

**Comment by someara** [comment]
This should be fixed up now that 8acc065346f2fdef441a59b72285963dafd488c9 is merged
