### ISSUE TITLE
Provide a way to make `yum clean REPO_NAME` optional

### ISSUE THREAD

**Issue by ketan** [chef-cookbooks/yum#127]
We're testing a bunch of cookbooks using kitchen and [vagrant-cachier](https://github.com/fgrehm/vagrant-cachier) to cache yum, apt, rubygems and a few other packages.

However the `yum clean` operation that [got added](https://github.com/chef-cookbooks/yum/commit/ecdbc2b00dd5d1d33bf8ab0454bbd65edfbfd7de) in version 3.6 is a bit of an inconvenience because it blows away all yum caches.

I'm happy to submit a PR to make that behaviour optional by specifying a `yum_clean` (?) parameter that defaults to `true`, but can be turned off if desired.

Thoughts?

/cc @someara (the original author who added that line of code)

**Comment by andytson** [comment]
either disable it by default, or make it optional with `yum clean headers` being used instead of `yum clean all`

**Comment by someara** [comment]
feature added in abe430dd806bfc3df250a868526c186aa2326922

**Comment by someara** [comment]
released in 3.8.0

**Comment by ketan** [comment]
Thanks a bunch
