### ISSUE TITLE
yum fails to install packages, works manually

### ISSUE THREAD

**Issue by kplimack** [chef-cookbooks/yum#130]
I've tried cleaning, making fresh caches, etc.  no luck.

Recipe: python::package
  * yum_package[python] action install (up to date)
  * yum_package[python-devel] action install

    ================================================================================
    Error executing action `install` on resource 'yum_package[python-devel]'
    ================================================================================

    Chef::Exceptions::Exec
    ----------------------
    yum -d0 -e0 -y install python-devel-2.6.6-51.el6 returned 1:
    STDOUT:
    STDERR:

    Error Downloading Packages:
      python-devel-2.6.6-51.el6.x86_64: failure: python-devel-2.6.6-51.el6.x86_64.rpm from oracle_linux_base_6: [Errno 256] No more mirrors to try.

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/python/recipes/package.rb

     41:   package pkg do
     42:     action :install
     43:   end
     44: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/python/recipes/package.rb:41:in `block in from_file'

    yum_package("python-devel") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      package_name "python-devel"
      version "2.6.6-51.el6"
      flush_cache {:before=>false, :after=>false}
      declared_type :package
      cookbook_name "python"
      recipe_name "package"
    end

Running handlers:
[2015-08-31T17:51:16+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-08-31T17:51:16+00:00] ERROR: Exception handlers complete
Chef Client failed. 1 resources updated in 6.802199844 seconds
[2015-08-31T17:51:16+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-08-31T17:51:16+00:00] ERROR: yum_package[python-devel] (python::package line 41) had an error: Chef::Exceptions::Exec: yum -d0 -e0 -y install python-devel-2.6.6-51.el6 returned 1:
STDOUT:
STDERR:

Error Downloading Packages:
  python-devel-2.6.6-51.el6.x86_64: failure: python-devel-2.6.6-51.el6.x86_64.rpm from oracle_linux_base_6: [Errno 256] No more mirrors to try.

[2015-08-31T17:51:16+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
[root@derp ~]# chef-client -v
Chef: 12.4.1
[root@derp ~]# yum -d0 -e0 -y install python-devel-2.6.6-51.el6
[root@derp ~]# echo $?
0
[root@derp ~]# rpm -q python-devel-2.6.6-51.el6
python-devel-2.6.6-51.el6.x86_64

**Comment by Gazzonyx** [comment]
What happens if you bump the retries to like 3?

**Comment by kplimack** [comment]
i think it was weird proxy settings that was causing this

**Comment by asifrc** [comment]
@kplimack We're you ever able to fix the issue? I'm currently facing the same problem.

**Comment by someara** [comment]
PS: This issue is about yum_package resource, which ships in core Chef, not the yum cookbook.

**Comment by kplimack** [comment]
my issue was because i'm behind a proxy.  when I ran yum manually, my ENV's
HTTP{S,}_PROXY was used, but chef-client didn't use my ENV.
the fix was getting the right packages into my internal repos and removing
the need for a proxy

**Comment by someara** [comment]
What version of Chef are you on?
Can you report this on the chef/chef repository?

-s

**Comment by alex1007** [comment]
I have a problem with yum_package[python-dev]
=============================================================================
Error executing action `install` on resource 'yum_package[python-dev]'
=============================================================================
Chef::Exceptions::Package
-------------------------
No candidate version available for python-dev
