### ISSUE TITLE
DNF support

### ISSUE THREAD

**Issue by st-isidore-de-seville** [chef-cookbooks/yum#132]
Will DNF support be included soon?  I think there was a DNF workaround included in Chef: https://github.com/chef/chef/pull/3774

**Comment by someara** [comment]
Hi. What exactly would be required to support DNF from this cookbook?

**Comment by st-isidore-de-seville** [comment]
From just taking a cursory look, I think it would just be mapping the "yum" commands to "dnf" commands like: https://fedoraproject.org/wiki/Yum_to_DNF_Cheatsheet  They tried to keep a one to one mapping but some are different.  If you want, I can attempt to map out what is your cookbook would have to change.  Assuming we are on the same page, I could then attempt a PR if you are willing.

**Comment by someara** [comment]
Ah okay. So this would be in chef/chef against the package resource, not chef-cookbooks/yum. 




I'm pretty sure this is already being worked on but you should open an issue there.




Closing this here.




-s



—

**Comment by st-isidore-de-seville** [comment]
What I am referring to here is not the creation or management of a dnf_package resource like a yum_package resource, I am referring to how the repositories are managed.  From what I can tell, the DNF repository configuration is the same as the YUM repository configuration.  The only difference is the main configuration is located at /etc/dnf/dnf.conf.  See http://dnf.readthedocs.org/en/latest/conf_ref.html for an explanation.  

I guess the point I am getting to get to is the fact that since DNF is the upgrade to YUM and they are managed in "almost" exactly the same way, should this cookbook support the DNF that is used in the newer Fedora environments?  Otherwise those guys are without repository management in Chef until this gets resolved.

**Comment by someara** [comment]
reopening

**Comment by someara** [comment]
The latest release makes yum_repository happy on fedora-22, so I'm going to close this for now.

**Comment by st-isidore-de-seville** [comment]
awesome @someara.  just out of curiosity is there something we should probably be doing for a long term fix or should I just raise that issue as it arises?

**Comment by someara** [comment]
I believe there's a DNF package provider being worked on, which is
definitely needed.

As for repository configuration, if DNF proves to be different enough than
yum to warrant a separate dnf_repository resource that "provides
:yum_repository" on the appropriate platforms, we can cross that bridge
when we get to it.

-s
