### ISSUE TITLE
'Deprecated features used!' warning message

### ISSUE THREAD

**Issue by kongakong** [chef-cookbooks/yum#140]
Warning message from Chef 13

    ==> Server-003: Deprecated features used!
    
    ==> Server-003:   Cannot specify both default and name_property together on property path of resource yum_globalconfig. Only one (name_property) will be obeyed. In Chef 13, this will become an error. at 1 location:
    
    ==> Server-003:     - /var/chef/cache/cookbooks/yum/resources/globalconfig.rb:76:in `class_from_file'
    
    ==> Server-003:   version nil currently does not overwrite the value of version. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :version, [MyType, nil]", or stop setting this value to nil. at 3 locations:
    
    ==> Server-003:     - /var/chef/cache/cookbooks/python/recipes/pip.rb:52:in `block in from_file'
    
    ==> Server-003:     - /var/chef/cache/cookbooks/python/recipes/virtualenv.rb:25:in `block in from_file'
    
    ==> Server-003:     - /var/chef/cache/cookbooks/python/providers/pip.rb:98:in `load_current_resource'

**Comment by someara** [comment]
Hello!

We'll be working on getting rid of all these messages for a bit. Thanks for
reporting =)

-s

**Comment by levmichael3** [comment]
I can see that chef-client version does not cry about it while 12.5.1 does, am I correct?

**Comment by someara** [comment]
Fixed up in 3.8.1
