### ISSUE TITLE
"releasever" should be set to "latest" on Amazon Linux

### ISSUE THREAD

**Issue by whysthatso** [chef-cookbooks/yum#142]
not entirely sure if this is the right place.

one of my dependencies uses the yum cookbook version  ~>3.6 and i've come to realize that it removes the pair `releasever=latest` from `/etc/yum.conf`, thereby breaking the rolling release mechanism of Amazon's distro. This should probably be considered, as the default in this cookbook equals nil, afaik.

does that make sense?

**Comment by iennae** [comment]
Thanks for the report @whysthatso. Apologies for the delay in resolving, this will be fixed in the next release of the yum cookbook.

**Comment by iennae** [comment]
Version 3.12.0 of this cookbook should implement this as expected. Please let us know if it doesn't. Thanks!
