### ISSUE TITLE
Support for `createrepo`

### ISSUE THREAD

**Issue by arthurbarr** [chef-cookbooks/yum#145]
Enhancement request: it would be helpful if this cookbook could help use `createrepo` to create a local repository.  This could either be another resource, or a property on the `repository` resource.

**Comment by st-isidore-de-seville** [comment]
I have a cookbook with similar functionality that I use in cases where software is distributed as an RPM but its not included in a formal repository.

:+1:

**Comment by tas50** [comment]
I think this is outside the scope of this cookbook. There are a few repo cookbooks out there and this is something better done in those.
