### ISSUE TITLE
diskspacecheck parameter cannot be set to 'false'

### ISSUE THREAD

**Issue by PygmySurfer** [chef-cookbooks/yum#146]
If you attempt to set 'diskspacecheck' to 'false', the diskspacecheck parameter does not get written to the config file at all.  Because the parameter defaults to true, there is no way to set it to false via this cookbook.

**Comment by iennae** [comment]
@PygmySurfer 

Apologies for the delay in responding to this issue. I checked using the fixture cookbook recipe yum_test::test_globalconfig_two, and I see that diskspacecheck works fine. The parameter defaults to nil, and you can override it as needed. What are you doing to try to test this?

**Comment by iennae** [comment]
If you are still having a problem, please reopen.
