### ISSUE TITLE
yum_repository support for :enable and :disable repositories

### ISSUE THREAD

**Issue by st-isidore-de-seville** [chef-cookbooks/yum#148]
I have a use case where I am using a third party cookbook which installs a rpm package via a yum repository on a RHEL 7 OS in AWS.  The problem I am experiencing is that the rpm package is in a RHEL optional repository that is not enabled by default.  I figured with this cookbook, I could own the AWS RHEL repository and create definitions for all of the various AWS RHEL repositories.  

However instead of doing that, it may be an interesting use case (since this cookbook effectively owns the yum_repository namespace :smile: ) if yum_repository could have two actions to enable and disable a repository without having to own the entire repository definition.  I figured behind the scenes it would perform a `yum-config-manager --enable` or `yum-config-manager --disable` behind the scenes.  

If this is something that you think would fit into the purview of this cookbook, I would be more than happy to whip something up.  

Just wanted to run this past you before doing so.

Thanks!

**Comment by jmaziarz** [comment]
+1

**Comment by netflash** [comment]
+1

**Comment by acholt** [comment]
+1

**Comment by kierandelaney** [comment]
+1

**Comment by stephan2012** [comment]
+1

**Comment by tas50** [comment]
We've moved yum_repository to core chef. Any feature requests should be done there now
