### ISSUE TITLE
Resolve Chef 13 deprecation warning

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/yum#151]
Deprecated features used!
         Cannot specify both default and name_property together on property path of resource yum_globalconfig. Only one (name_property) will be obeyed. In Chef 13, this will become an error. at 1 location:
           - /tmp/kitchen/cache/cookbooks/yum/resources/globalconfig.rb:77:in `class_from_file'

**Comment by someara** [comment]
This is a bug in Chef / compat_resource

https://github.com/chef-cookbooks/compat_resource/issues/40

**Comment by tas50** [comment]
Closing this since it's a compat_resource bug
