### ISSUE TITLE
Yum cache should be purged before repository config file is deleted

### ISSUE THREAD

**Issue by icberg7** [chef-cookbooks/yum#152]
The `yum clean` command only operates against repositories that are currently defined and enabled.
From the yum man page:
>CLEAN OPTIONS
>       The following are the ways which you can invoke yum in clean mode. Note
>       that  "all  files"  in the commands below means "all files in currently
>       enabled repositories".  If you want to  also  clean  any  (temporarily)
>       disabled repositories you need to use --enablerepo=’*’ option.

In the provider, the repository config file is deleted and then the cache is cleaned; however, this means that the cache is left intact for the cache that you just removed.
It looks like the provider is trying to explicitly enable the deleted repo, but if you try this on a box with a repo that's undefined, you get an error:

```
[root@server01 yum]# yum clean all --disablerepo=* --enablerepo=chef_stable
Loaded plugins: security


Error getting repository data for chef_stable, repository not found
```

The provider should try to flush the cache first, delete the repository file, and then reload the cache.

A `:before` timer could be used instead of `:immediately`, but that is only supported in Chef 12+ somewhere. Alternatively, an `only_if` block could be used to test for the file's existence, which would preserve chef 11 support.

**Comment by icberg7** [comment]
Actually, because of this line, the cache is not actually deleted: https://github.com/chef-cookbooks/yum/blob/master/providers/repository.rb#L91, as `yum repolist` will only show the repositories that are defined.

**Comment by haidangwa** [comment]
The problem with the fix you proposed in the bug is that it doesn't actually delete all of the cache, including the repo's cache directory. Execution of yum clean on the repo's cache directory only clears out some of the cruft left behind. A full directory deletion does a more thorough job.

```
    directory "#{yum_cachedir}/#{repo}" do
      action :delete
      recursive true
    end
```
