### ISSUE TITLE
Shouldn't README not include an example for EPEL?

### ISSUE THREAD

**Issue by jblaine** [chef-cookbooks/yum#153]
yum-epel should be used. README shows an example of `yum_repository` to set up EPEL.

Give me a verdict and I will submit a README patch with some other tiny typo fixes as well.

**Comment by tas50** [comment]
I'd agree that the choice of yum-epel was probably pretty poor.  If you want to create a PR for this I'd gladly merge it. Just use some fake internal company repo.
