### ISSUE TITLE
baseurl should support multiple url per documentation 

### ISSUE THREAD

**Issue by sclark007** [chef-cookbooks/yum#155]
### Cookbook version
 - yum (3.10.0)

### Chef-client version
Starting Chef Client, version 12.9.41

### Platform Details
CentOS 6.7 

### Scenario:
Per the baseurl documentation i expect to be able to specify multiple url. 

_baseurl - Must be a URL to the directory where the yum repository's 'repodata' directory lives. Can be an http://, ftp:// or file:// URL. You can specify multiple URLs in one baseurl statement._

### Steps to Reproduce:

yum_repository 'centos' do
  description "demo"
  baseurl [ 'http://mirror.hmc.edu/centos/6.7/os/x86_64/',  'http://mirrors.liquidweb.com/CentOS/6.7/os/x86_64/ ]
  gpgkey 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6'
  action :create
end

### Expected Result:
this should produce 1 baseurl entry and the addition entry should be url. as in manpage 
reference http://linux.die.net/man/5/yum.conf

baseurl Must be a URL to the directory where the yum repository's 'repodata' directory lives. Can be an http://, ftp:// or file:// URL. You can specify multiple URLs in one baseurl statement. The best way to do this is like this:

[repositoryid]
name=Some name for this repository
baseurl=url://server1/path/to/repository/
url://server2/path/to/repository/
url://server3/path/to/repository/

### Actual Result:
only produces a single baseurl

**Comment by iennae** [comment]
@sclark007 Thanks for the report! Apologies for the delay in resolving, but version 3.12.0 of this cookbook should implement this as expected.

**Comment by jagan495** [comment]
still its not working in chef-client Chef: 13.1.31, its only taking first url. Any suggestions please

**Comment by jagan495** [comment]
As per this chef doc https://docs.chef.io/resource_yum_repository.html and   url https://github.com/chef-cookbooks/yum/issues/155, baseurl should supports multiple urls in yum_repository resource, but after executing the code its listing packages from only firsturl . Here is my code..


  yum_repository 'ade_repo' do
    description "ade_repo"
    baseurl  ['http://xxxxxx-yum-xxxx-01.us.xxx.com/xxxx/LOB/xxx/ADE/x86_64/','http://xxxxx-yum-xxxx-01.us.xxx.com/xxxx/xxxxx', 'http://xxxx-yum-xxx.02.com/xxxxxxxxxxxxxxxxxxx']
    metadata_expire=0
    action :create
  end


Generated repo after chef-client run
======
# This file was generated by Chef
# Do NOT modify this file by hand.

[ade_repo]
name=ade_repo
baseurl=http://xxxxxx-yum-xxxx-01.us.xxx.com/xxxx/LOB/xxx/ADE/x86_64/
http://xxxxx-yum-xxxx-01.us.xxx.com/xxxx/xxxxx  
http://xxxx-yum-xxx.02.com/xxxxxxxxxxxxxxxxxxx  
enabled=1
fastestmirror_enabled=0
gpgcheck=1

Actual Result:
but here problem is we are able to list the packages from only 1st url but not from the 2nd and 3rd urls. (http://xxxxx-yum-xxxx-01.us.xxx.com/xxxx/xxxxx  
http://xxxx-yum-xxx.02.com/xxxxxxxxxxxxxxxxxxx  )


Can you please check above code and suggest me.
