### ISSUE TITLE
Installation of packages on centos

### ISSUE THREAD

**Issue by sernapallyanurag** [chef-cookbooks/yum#157]
### Cookbook version
yum 3.10.0

### Chef-client version
 version 12.11.18

### Platform Details
Centos openlogic- 7.1 azure VM

### Scenario:
I want to install these packages
gcc gcc-c++ graphviz graphviz-devel patchutils gd gd-devel wget perl* -x perl-homedir

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

### Expected Result:
Installation of above packages

How can I install them?

**Comment by tas50** [comment]
You can install these packages using the package resource in chef, which is built in and doesn't require this cookbook.  Take a look at https://docs.chef.io/resource_package.html
