### ISSUE TITLE
node['yum']['main']['exclude'] would be better as an array, no?

### ISSUE THREAD

**Issue by jblaine** [chef-cookbooks/yum#158]
### Cookbook version

3.11.0
### Chef-client version

12.6.0
### Platform Details

RHEL 6, 7
### Scenario:

Is there any reason, aside from backward compatibility with previous versions of this cookbook, why `node['yum']['main']['exclude']` is a space-separated string and not an array that then gets munged in the code for the `yum_globalconfig` resource? On the surface, an array makes much more sense for the data type, to me.

Maybe an array for a 4.0.0 release?

**Comment by jmaziarz** [comment]
After some experimentation with Chef's deep-merging, it appears that array attributes are unpredictable. Instead, as suggested at https://coderanger.net/arrays-and-chef/, consider making `node['yum']['main']['exclude']` a hash.

Unfortunately, `node['yum']['main']['exclude'] = { 'apache2' => true, 'splunkforwarder' => true }` *also* doesn't work as expected. The only way I've found Chef to predictably deep-merge a hash properly is to assign attributes as follows:

```
node['yum']['main']['exclude']['apache2'] = true
node['yum']['main']['exclude']['spunkforwarder'] = true
```

The use case we run into most often is having multiple cookbooks each defining a list of packages to be excluded. When `node['yum']['main']['exclude']` is a string, parsing gets messy very quickly. If a hash were used, support for multiple cookbooks would be a lot nicer.

**Comment by tas50** [comment]
As @jmaziarz mentioned above the way that arrays are merged makes this really difficult. While not using an array seems really odd it actually makes it a lot easier to use. I'm going to close this one out at this point in time.

**Comment by jmaziarz** [comment]
@tas50 Would you consider using a hash (as detailed above)?
