### ISSUE TITLE
yum makecache in a recipe

### ISSUE THREAD

**Issue by pantocrator27** [chef-cookbooks/yum#171]
### Scenario:
The apt Cookbook provides a mechanism to do an `apt-get update` as part of the chef run in its default recipe.  I am wondering if the yum Cookbook should provide a similar construct for parity which seems like it would be `yum makecache`

**Comment by cheeseplus** [comment]
What is the need for updating the cache in this scenario? Yum and certain other package managers update the cache as needed. Apt doesn't do this hence why we have that functionality for it.

**Comment by pantocrator27** [comment]
I guess my thinking was that whenever I spin up a server, before I bootstrap it to chef, I am always performing a `yum makecache` out of fear that the cache may be expired on the first boot of the server.  I agree that yum maintains its own cache and expiring rules.

**Comment by pantocrator27** [comment]
just curious if you received my response ...

**Comment by cheeseplus** [comment]
If you can provide a scenario it would be needed/required we'd be interested. But as stated earlier there isn't any reason we need to run this as yum automatically does so when installing packages. As such we don't have any intention of adding it at this time.
