### ISSUE TITLE
[QUESTION] yum cookbook backward compatibility promises

### ISSUE THREAD

**Issue by pantocrator27** [chef-cookbooks/yum#172]
### Cookbook version
5.0.0

### Question

I noticed that this cookbook is certified for use with Chef Client version 12.14+.  The question I have is that I would have thought the the community maintained cookbooks published by Chef would have the same backwards compatibility promise as the Chef Client (back to v12.0).  Is this no longer the case?  Just curious.

**Comment by cheeseplus** [comment]
Given that Chef 13 is just around the corner we have begun updating all our cookbooks to make sure they are compatible. You can still use an older version of the cookbook for further backward compatibility, `4.2.0` for example. For this cookbook in particular, most of the resources have moved into core chef and so the version restriction was bumped a major to make it clear this was a breaking change and largely to ensure other cookbooks which may depend on this one do not break.

We're moving to a yearly major release with 13 which should help alleviate having a multi-year major version which contributed to the state we find ourselves.
