### ISSUE TITLE
enabling a yum repo should implicitly set the `manage` attribute to true

### ISSUE THREAD

**Issue by haidangwa** [chef-cookbooks/yum#174]
### Cookbook version
4.1.0

### Chef-client version
12.14.89

### Platform Details
redhat 6

### Scenario:
I intended to enable a yum repo, but setting only the yum/<repo>/enable attribute doesn't do the trick. It also requires setting the yum/<repo>/managed attribute to true before a file is dropped onto /etc/yum.repos.d/<repo>.repo.

### Steps to Reproduce:
in a role, set the enabled attribute to true:
```
    "yum": {
      "remi": {
        "enabled": true
      }
    }
```

### Expected Result:
I should see /etc/yum.repos.d/remi.repo on the target node. Setting the enabled attribute should imply that the managed attribute is also true.

### Actual Result:
nothing is created.

**Comment by iennae** [comment]
@haidangwa this looks like you are having an expectation of behaviors around the [yum-remi-chef](https://github.com/chef-cookbooks/yum-remi-chef) cookbook. The yum-remi-chef cookbook recipes expect that node['yum'][repo]['managed'] is set to true or it doesn't configure the repo. Take a look at this [recipe](https://github.com/chef-cookbooks/yum-remi-chef/blob/master/recipes/remi-php71.rb#L30). This doesn't have anything to do with the yum cookbook so I'm going to go ahead and close this issue. If you want to submit a pull request to the yum-remi-chef cookbook to update this behavior this will give folks who use the cookbook the space and time to evaluate the proposed change.

Thanks.
