### ISSUE TITLE
5.1.0 is not available from the supermarket

### ISSUE THREAD

**Issue by rbogdany** [chef-cookbooks/yum#177]
### Cookbook version
5.1.0

### Chef-client version
12.13.37

### Platform Details
macOS

### Scenario:
Trying to download yum 5.1.0 from the chef supermarket

### Steps to Reproduce:
knife cookbook site show yum

### Expected Result:
expect knife to show 5.1.0 version since it was release back in Aug per the CHANGELOG

### Actual Result:
Only shows the 5.0.1 version
```6:42 $ knife cookbook site show yum
average_rating:  
category:        Other
created_at:      2011-04-20T22:16:12.000Z
deprecated:      false
description:     Configures various yum components on Red Hat-like systems
external_url:    https://github.com/chef-cookbooks/yum
issues_url:      https://github.com/chef-cookbooks/yum/issues
latest_version:  https://supermarket.chef.io/api/v1/cookbooks/yum/versions/5.0.1
```

**Comment by iennae** [comment]
Thanks for reporting this. It's been released to supermarket now.
