### ISSUE TITLE
Not using downloaded repomd.xml because it is older than what we have

### ISSUE THREAD

**Issue by mconigliaro** [chef-cookbooks/yum#96]
`yum makecache` fails inside the `yum_repository` provider when you point to a mirror with an older `repomd.xml` than what has already been downloaded. This could happen if you start out pointing to an official mirror, then reconfigure yum to point to your own local mirror (which may not have had a chance to sync up yet):

```
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of yum -q makecache --disablerepo=* --enablerepo=foo ----
STDOUT:
STDERR: Not using downloaded repomd.xml because it is older than what we have:
 Current  : Tue Oct  7 15:14:53 2014
 Downloaded: Thu Oct  2 15:00:04 2014
http://example.com/repodata/filelists.xml.gz: [Errno -1] Metadata file does not match checksum
Trying other mirror.
Error: failure: repodata/filelists.xml.gz from foo: [Errno 256] No more mirrors to try.
---- End output of yum -q makecache --disablerepo=* --enablerepo=foo ----
Ran yum -q makecache --disablerepo=* --enablerepo=foo returned 1
```

I *think* the solution is to run a `yum clean` before running `yum makecache`. Unless there's some flag I'm missing to force yum to use the older repomd.xml.

**Comment by someara** [comment]
what is the lightest test you can think of to detect this condition?

**Comment by Gazzonyx** [comment]
I figured out how we're hitting this bug and I've got a simple-ish test case.  Basically we've got a race condition between our local yum repos and the upstream yum repos.  

Our workflow is that we automatically provision a hardware appliance with cobbler, reboot, run the first run setup to set hostname (as we use chef vault and have to have our node registered with a known name) and then reboot and bootstrap the chef client.

When we run our chef converge, usually within five to ten minutes from when the appliance was first provisioned, our cookbook changes the location of the repositories to our local mirrors and sometimes those mirrors are behind the upstream yum repositories by up to an hour.

**Comment by mconigliaro** [comment]
It's been a while since I've looked at this, but to summarize my comments above, I believe the solution is to run `yum clean metadata --disablerepo=* --enablerepo=foo` just before running `yum makecache --disablerepo=* --enablerepo=foo` (presumably every time the `foo` repository config file is changed).

**Comment by mconigliaro** [comment]
@someara I don't think this is something you'd want to "detect" per-se. What I'm suggesting is that the `yum makecache` this cookbook currently does is only half of what needs to be done. I think you need to run `yum clean metadata` first in order to delete the old cache files.

**Comment by someara** [comment]
I've added a "yum clean" before the "yum makecache" in the :create action.
Released as 3.6.0

**Comment by mconigliaro** [comment]
:+1:

**Comment by Gazzonyx** [comment]
Awesome!  Thanks @someara!

**Comment by kplimack** [comment]
I'm setting this on oracle linux 6.5, chef  12.4.1
